pipeline_class: "ExperimentPipelineForClassifier" 
experiment_metadata:
  description: "CnnEncoderDecoder"
  tag: "CnnEncoderDecoder[PTB]"
dataloader_class_name: "PTBDataLoaderForAutoEncoder" #"BalancedMITBIHDataLoader"
val_split:  # validation split ratio should be None for AutoEncoder
model_class_name: CnnEncoderDecoder #"CnnEncoder" #"CnnPretrainEncoderWithTrainableClassifierHead"
load_from_checkpoint: false
checkpoint_path: ""
cost_function_class_name: "MSELoss"
trainer_class_name: "CnnTrainer"
num_epochs: 50
batch_size: 32
learning_rate: 0.001
weight_decay: 0.0000001
logdir: "runs"
test_batch_frequency: 500 # evaluate performance metrics on test data
#after these many batches have been processed
batch_log_frequency: 1 # Print log after after these many batches
tensorboard_log_frequency: 100 # Log scalars after these many batches
test_batch_size: 100
scheduler: 
