batch_log_frequency: 1
batch_size: 100
checkpoint_path: ''
cost_function_class_name: BCELoss
dataloader_class_name: PTBDataLoader
experiment_metadata:
  description: CNN + Residual connections applied to PTB dataset
  tag: exp_2_a_CnnWithResidualConnection[PTB]
generate_roc_curves: true
learning_rate: 0.001
load_from_checkpoint: false
logdir: runs
model_class_name: CnnWithResidualConnectionPTB
num_epochs: 100
pipeline_class: ExperimentPipelineForClassifier
scheduler: null
task_type: binary_classification
tensorboard_log_frequency: 100
test_batch_frequency: 500
test_batch_size: 100
trainer_class_name: CnnTrainer
val_split: 0.2
weight_decay: 1.0e-07
