batch_log_frequency: 1000
batch_size: 20
checkpoint_path: runs/2022-03-27_174617__CnnEncoderDecoder_Mitbih/best_model.ckpt
cost_function_class_name: MSELoss
dataloader_class_name: BalancedMITBIHDataLoaderForAutoEncoder
experiment_metadata:
  description: Trying out CNN autoencoder to learn features to be used laterfor classification.
  tag: CnnEncoderDecoder_Mitbih
learning_rate: 0.001
load_from_checkpoint: true
logdir: runs
model_class_name: CnnEncoderDecoder
num_epochs: 50
pipeline_class: ExperimentPipelineForAutoEncoder
scheduler: null
tensorboard_log_frequency: 1000
test_batch_size: 100
trainer_class_name: CnnTrainer
val_split: null
weight_decay: 1.0e-05
