pipeline_class: "ExperimentPipelineUnetAE" 
experiment_metadata:
  description: "Trying out autoencoder to learn features to be used later\
                for classification."
  tag: "unet_ae"
dataloader_class_name: "MITBIHDataLoaderForAutoEncoder"
model_class_name: "UnetEncoderDecoder"
load_from_checkpoint: false
checkpoint_path: ""
cost_function_class_name: "MSELoss"
trainer_class_name: "CnnTrainer"
num_epochs: 10
batch_size: 200
learning_rate: 0.001
weight_decay: 0.00001
logdir: "runs"
test_batch_frequency: 500 # evaluate performance metrics on test data
#after these many batches have been processed
batch_log_frequency: 200 # Print log after after these many batches
tensorboard_log_frequency: 200 # Log scalars after these many batches
test_batch_size: 100
