pipeline_class: "ExperimentPipelineUnetPretrained" 
experiment_metadata:
  description: "(NO LR scheduling)Checking how many epochs it take to get F1>=90.(\
                Trying out pretrained encoder and trainable classification \
               head. Pretraining was done in encoder-decoder pipeline.)"
  tag: "SimpleCnnWithResidualConnection"
dataloader_class_name: "MITBIHDataLoader" #"BalancedMITBIHDataLoader"
model_class_name: SimpleCnnWithResidualConnection #"CnnEncoder" #"CnnPretrainEncoderWithTrainableClassifierHead"
load_from_checkpoint: true
checkpoint_path: "runs/2022-03-24_113657__SimpleCnnWithResidualConnection/best_model.ckpt"
cost_function_class_name: "CrossEntropyLoss"
trainer_class_name: "CnnTrainer"
num_epochs: 70
batch_size: 200
learning_rate: 0.001
weight_decay: 0.0000001
logdir: "runs"
test_batch_frequency: 500 # evaluate performance metrics on test data
#after these many batches have been processed
batch_log_frequency: 1 # Print log after after these many batches
tensorboard_log_frequency: 100 # Log scalars after these many batches
test_batch_size: 100
scheduler: "ReduceLROnPlateau"
