batch_log_frequency: 150
batch_size: 200
checkpoint_path: ''
cost_function_class_name: CrossEntropyLoss
dataloader_class_name: MITBIHDataLoader
experiment_metadata:
  description: Vanilla CNN
  tag: exp_0_a_VanillaCnnMITBIH
learning_rate: 0.001
load_from_checkpoint: false
logdir: runs
model_class_name: VanillaCnnMITBIH
num_epochs: 100
pipeline_class: ExperimentPipelineForClassifier
scheduler: null
tensorboard_log_frequency: 100
test_batch_frequency: 500
test_batch_size: 100
trainer_class_name: CnnTrainer
val_split: 0.2
weight_decay: 1.0e-07
